apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.validatorName }}
  labels:
    app.kubernetes.io/name: kusama-validator
    app.kubernetes.io/instance: {{ .Values.validatorName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: prometheus
      port: {{ .Values.service.prometheusPort }}
      targetPort: prometheus
    {{- if .Values.haproxy.enabled }}
    - name: haproxy-stats
      port: 8404
      targetPort: stats
    {{- end }}
  selector:
    app.kubernetes.io/name: kusama-validator
    app.kubernetes.io/instance: {{ .Values.validatorName }}
---
{{- if and .Values.p2pNodePort.enabled (not .Values.haproxy.enabled) }}
# Legacy NodePort for P2P (only when HAProxy is disabled)
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.validatorName }}-p2p
  labels:
    app.kubernetes.io/name: kusama-validator
    app.kubernetes.io/instance: {{ .Values.validatorName }}
spec:
  type: NodePort
  ports:
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      {{- if .Values.p2pNodePort.port }}
      nodePort: {{ .Values.p2pNodePort.port }}
      {{- end }}
  selector:
    app.kubernetes.io/name: kusama-validator
    app.kubernetes.io/instance: {{ .Values.validatorName }}
{{- end }}
