apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.validatorName }}
  labels:
    app.kubernetes.io/name: kusama-validator
    app.kubernetes.io/instance: {{ .Values.validatorName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: ws
      port: {{ .Values.service.wsPort }}
      targetPort: ws
    - name: prometheus
      port: {{ .Values.service.prometheusPort }}
      targetPort: prometheus
  selector:
    app.kubernetes.io/name: kusama-validator
    app.kubernetes.io/instance: {{ .Values.validatorName }}
---
{{- if .Values.p2pNodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.validatorName }}-p2p
  labels:
    app.kubernetes.io/name: kusama-validator
    app.kubernetes.io/instance: {{ .Values.validatorName }}
spec:
  type: NodePort
  ports:
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      {{- if .Values.p2pNodePort.port }}
      nodePort: {{ .Values.p2pNodePort.port }}
      {{- end }}
  selector:
    app.kubernetes.io/name: kusama-validator
    app.kubernetes.io/instance: {{ .Values.validatorName }}
{{- end }}
